apiVersion: argoproj.io/v1alpha1

kind: Application

metadata:
  name: site-poc-levva-devops
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io

spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: devops-space
  project: default
  source:
    repoURL: 'https://github.com/claudioferejes/argocd-site-poc.git'
    path: site-helm
    targetRevision: HEAD
    helm:
      valueFiles:
      - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true
